export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const AUTH_LOADING = 'AUTH_LOADING';

export const GET_APARTMENT_SUCCESS = 'GET_APARTMENT_SUCCESS';
export const GET_APARTMENT_ERROR = 'GET_APARTMENT_ERROR';

export const GET_SHARED_SUCCESS = 'GET_SHARED_SUCCESS';
export const GET_SHARED_ERROR = 'GET_SHARED_ERROR';

export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_ERROR = 'GET_ALL_BLOG_ERROR';
export const BLOG_LOADING = 'BLOG_LOADING';

export const TOGGLE_LIGHT_BOX = 'TOGGLE_LIGHT_BOX';

export const UPLOAD_LOADING = 'UPLOAD_LOADING';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';

export const TOGGLE_DONE_MODAL = 'TOGGLE_DONE_MODAL';

export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const SEND_REQUEST_ERROR = 'SEND_REQUEST_ERROR';
